platform :ios, '9.0'

target 'ProxiChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProxiChat
pod 'ChameleonFramework'
pod 'SwiftyJSON'
pod 'Socket.IO-Client-Swift'
pod 'SVProgressHUD'
end
